# Generated by Django 5.2.4 on 2025-07-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_profile_message_chat_messag_sender__4e0fb2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__4e0fb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_recipie_c405d1_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default="Hey there! I'm using EliteChat", max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
